# Generated by Django 4.2.4 on 2023-09-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=255)),
                ('prix', models.BigIntegerField()),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
