# Generated by Django 4.2.4 on 2023-09-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('civilite', models.CharField(choices=[('MR', 'Mr'), ('MME', 'Mme')], max_length=50)),
                ('fonction', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('admin', 'Admin'), ('developer', 'Developer'), ('utilisateur', 'Utilisateur')], default='Utilisateur', max_length=100)),
                ('status', models.CharField(choices=[('activer', 'Activer'), ('desactiver', 'Desactiver'), ('suspendu', 'Suspendu'), ('en attente', 'En Attente')], default='En Attente', max_length=100)),
            ],
        ),
    ]
