# Generated by Django 4.2.4 on 2023-09-11 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('en attente', 'En Attente'), ('en cours de traitement', 'En Cours De Traitement'), ('expedier', 'Expedier'), ('livrer', 'Livrer'), ('annuler', 'Annuler')], max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='client.client')),
            ],
        ),
    ]
