# Generated by Django 4.2.4 on 2023-09-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0001_initial'),
        ('commande', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='produits',
            field=models.ManyToManyField(to='produit.produit'),
        ),
    ]
